// leekWeapon.js
export const ADD_LEEKWEAPON_TO_LIST = 'leekWeapon/ADD_LEEKWEAPON_TO_LIST'
export const REMOVE_LEEKWEAPON_TO_LIST = 'leekWeapon/REMOVE_LEEKWEAPON_TO_LIST'
export const REMOVE_LEEKWEAPON_SUB_TO_LEVEL = 'leekChip/REMOVE_LEEKWEAPON_SUB_TO_LEVEL'
// leekChip.js
export const ADD_LEEKCHIP_TO_LIST = 'leekChip/ADD_LEEKWEAPON_TO_LIST'
export const REMOVE_LEEKCHIP_TO_LIST = 'leekChip/REMOVE_LEEKCHIP_TO_LIST'
export const REMOVE_LEEKCHIP_SUB_TO_LEVEL = 'leekChip/REMOVE_LEEKCHIP_SUB_TO_LEVEL'
// leekStats.js
export const SET_FREQUENCY = 'leekStats/SET_FREQUENCY'
export const SET_LIFE = 'leekStats/SET_LIFE'
export const SET_MAGIC = 'leekStats/SET_MAGIC'
export const SET_MP = 'leekStats/SET_MP'
export const SET_RESISTANCE = 'leekStats/SET_RESISTANCE'
export const SET_SCIENCE = 'leekStats/SET_SCIENCE'
export const SET_STRENGTH = 'leekStats/SET_STRENGTH'
export const SET_TP = 'leekStats/SET_TP'
export const SET_WISDOM = 'leekStats/SET_WISDOM'
export const SET_AGILITY = 'leekStats/SET_AGILITY'
export const SET_LEVEL = 'leekStats/SET_LEVEL'
